# Generated by Django 3.2.9 on 2022-01-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='resume',
            field=models.FileField(default='', upload_to='job/employee/resumes'),
        ),
    ]
