# Generated by Django 3.2.9 on 2022-01-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_applicant_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(default='', upload_to='employee/resumes'),
        ),
    ]
